# Generated by Django 5.2 on 2025-04-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_otp_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
